version: '3'

services:
  api:
    build: .
    container_name: S2T-api
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 80"
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - data_volume: /backend
